[build]
  publish = "."
  command = "cd netlify/functions/analyze-image && npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200